version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      node-workspaces:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /apps/services
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /infra/terraform/envs/staging
    schedule:
      interval: weekly
