sonar.projectKey=tachian_super-trunfo-nft
sonar.organization=tachian
sonar.projectName=super-trunfo-nft

sonar.sources=apps,packages,smart-contracts
sonar.tests=apps,packages,smart-contracts

sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/coverage/**,**/__pycache__/**,**/.cache/**,**/tests/**,**/*.test.ts,**/*.test.tsx,**/*_test.dart,smart-contracts/test/**,infra/**,**/*.generated.*,**/generated/**
sonar.test.inclusions=**/tests/**,**/*.test.ts,**/*.test.tsx,**/*_test.dart,smart-contracts/test/**
sonar.coverage.exclusions=apps/web/**,apps/mobile/**,smart-contracts/**,packages/api-contracts/**,**/tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=.coverage-reports/python/coverage.xml

sonar.sourceEncoding=UTF-8
