apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: platform-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: staging
      - op: replace
        path: /data/FEATURE_NFT_ENABLED
        value: "false"
replicas:
  - name: auth-service
    count: 2
  - name: card-service
    count: 2
  - name: matchmaking-service
    count: 2
  - name: gameplay-service
    count: 2
images:
  - name: super-trunfo/auth-service
    newName: ghcr.io/OWNER/REPO/auth-service
    newTag: main
  - name: super-trunfo/card-service
    newName: ghcr.io/OWNER/REPO/card-service
    newTag: main
  - name: super-trunfo/matchmaking-service
    newName: ghcr.io/OWNER/REPO/matchmaking-service
    newTag: main
  - name: super-trunfo/gameplay-service
    newName: ghcr.io/OWNER/REPO/gameplay-service
    newTag: main
  - name: super-trunfo/economy-service
    newName: ghcr.io/OWNER/REPO/economy-service
    newTag: main
  - name: super-trunfo/ranking-service
    newName: ghcr.io/OWNER/REPO/ranking-service
    newTag: main
  - name: super-trunfo/nft-service
    newName: ghcr.io/OWNER/REPO/nft-service
    newTag: main
  - name: super-trunfo/social-service
    newName: ghcr.io/OWNER/REPO/social-service
    newTag: main
  - name: super-trunfo/notification-service
    newName: ghcr.io/OWNER/REPO/notification-service
    newTag: main
  - name: super-trunfo/web
    newName: ghcr.io/OWNER/REPO/web
    newTag: main

