apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: super-trunfo
resources:
  - namespace.yaml
  - configmap.yaml
  - services.yaml
  - web.yaml
  - ingress.yaml
  - observability.yaml
commonLabels:
  app.kubernetes.io/part-of: super-trunfo-nft
