apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: super-trunfo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tachian/super-trunfo-nft.git
    targetRevision: main
    path: infra/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: super-trunfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
